env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_NEED_GCC: 1
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  android-arm64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpl
  android-x86_64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpl
  linux-arm64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpl
  linux-ppc64le:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpl
  linux-x86_64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpl
  macosx-arm64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpl
  macosx-x86_64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpl
  redeploy:
    needs:
    - android-arm64
    - android-x86_64
    - linux-arm64
    - linux-ppc64le
    - linux-x86_64
    - macosx-arm64
    - macosx-x86_64
    - windows-x86_64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
  windows-x86_64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpl
name: ffmpeg
on:
  repository_dispatch:
    types: trigger-ga___ffmpeg.yml
