env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_NEED_BAZEL: 1
  CI_DEPLOY_NEED_CUDA: 1
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  android-arm:
    container: centos:7
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  android-arm64:
    container: centos:7
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  android-x86:
    container: centos:7
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  android-x86_64:
    container: centos:7
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  linux-x86:
    container: centos:7
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  linux-x86_64:
    container: centos:7
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpu
  macosx-x86_64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  redeploy:
    needs:
    - android-arm
    - android-arm64
    - android-x86
    - android-x86_64
    - linux-x86
    - linux-x86_64
    - macosx-x86_64
    - windows-x86_64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
  windows-x86_64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: al-cheb/configure-pagefile-action@v1.3
      with:
        disk-root: 'C:'
        maximum-size: 32GB
        minimum-size: 16GB
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
    strategy:
      matrix:
        ext:
        - ''
        - -gpu
name: tensorflow
on:
  repository_dispatch:
    types: trigger-ga___tensorflow.yml
