env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86_64:
    container: nvcr.io/nvidia/tritonserver:24.03-py3
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
name: tritonserver
on:
  repository_dispatch:
    types: trigger-ga___tritonserver.yml
