env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  redeploy:
    needs:
    - windows-x86
    - windows-x86_64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
  windows-x86:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  windows-x86_64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
name: videoinput
on:
  repository_dispatch:
    types: trigger-ga___videoinput.yml
